---
- name: log
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - logging
    - db 


- name: sonbm
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common
    - web
    - api
    - monitor

- name: lb
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - lb

